spring:
  application:
    name: Journal App
  data:
    mongodb:
      uri: mongodb+srv://soumo:admin123@springbootcluster.w695meq.mongodb.net/?retryWrites=true&w=majority&appName=SpringBootCluster
      database: journalDB
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 9090
  servlet:
    context-path: /journal